[package]
name = "blog-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
axum = { version = "0.8.4", features = ["tokio", "macros", "http1"] }
tokio = { version = "1.46.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"